# Generated by Django 2.2.19 on 2021-04-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('merk', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField()),
                ('jenis', models.CharField(max_length=100)),
                ('keterangan', models.CharField(blank=True, max_length=250, null=True)),
                ('Foto', models.FileField(blank=True, default='barang.jpg', null=True, upload_to='')),
                ('tanggal_diupload', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
