# Generated by Django 2.2.19 on 2021-04-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengawas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='barang',
        ),
    ]
