# Generated by Django 2.2.19 on 2021-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('merk', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=0)),
                ('jenis', models.CharField(max_length=100)),
                ('satuan', models.CharField(max_length=100)),
                ('keterangan', models.CharField(blank=True, max_length=250, null=True)),
                ('Foto', models.FileField(blank=True, default='barang.jpg', null=True, upload_to='')),
                ('tanggal_diupload', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='jenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('deskripsi', models.CharField(max_length=250)),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('nip', models.CharField(max_length=250, unique=True)),
                ('pangkat', models.CharField(max_length=100)),
                ('golongan', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=250)),
                ('Foto', models.FileField(blank=True, default='karyawan.jpg', null=True, upload_to='')),
                ('tanggal_terdaftar', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='peminjaman_barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_peminjam', models.CharField(max_length=250)),
                ('nama_peminjam', models.CharField(max_length=250)),
                ('nama_barang', models.CharField(max_length=250)),
                ('status_peminjaman', models.CharField(default='1', max_length=100)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('id_barang', models.PositiveIntegerField(default=0)),
                ('id_op', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='pengembalian_barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaksi', models.PositiveIntegerField()),
                ('nip_pengembali', models.CharField(max_length=250)),
                ('nama_pengembali', models.CharField(max_length=250)),
                ('nama_barang', models.CharField(max_length=250)),
                ('status_pengembalian', models.CharField(default='1', max_length=100)),
                ('tanggal_kembali', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(max_length=250, null=True)),
                ('id_op', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
