# Generated by Django 2.2.19 on 2021-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='keterangan',
            field=models.CharField(blank=True, default='-', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pengembalian_barang',
            name='keterangan',
            field=models.CharField(default='-', max_length=250, null=True),
        ),
    ]
