# Generated by Django 2.2.19 on 2021-05-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0002_auto_20210430_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='kode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
