# Generated by Django 2.2.19 on 2021-05-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0003_barang_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
