# Generated by Django 2.2.19 on 2021-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0004_auto_20210521_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='status',
            field=models.CharField(default='Tersedia', max_length=100),
        ),
    ]
