# Generated by Django 2.2.19 on 2021-05-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0005_auto_20210521_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman_barang',
            name='id_op',
        ),
        migrations.AlterField(
            model_name='peminjaman_barang',
            name='status_peminjaman',
            field=models.CharField(default='Dipinjam', max_length=100),
        ),
        migrations.AlterField(
            model_name='pengembalian_barang',
            name='status_pengembalian',
            field=models.CharField(default='Dikembalikan', max_length=100),
        ),
    ]
