# Generated by Django 2.2.19 on 2021-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0009_pengembalian_barang_nama_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('merk_barang', models.CharField(max_length=100)),
                ('jenis_barnag', models.CharField(max_length=100)),
                ('id_barang', models.CharField(max_length=100)),
            ],
        ),
    ]
