# Generated by Django 2.2.19 on 2021-05-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0010_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='jenis_barnag',
            new_name='jenis_barang',
        ),
    ]
