# Generated by Django 2.2.19 on 2021-05-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0011_auto_20210527_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temp',
            new_name='keranjang',
        ),
    ]
