# Generated by Django 2.2.19 on 2021-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0012_auto_20210527_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman_barang',
            name='kode_pinjam',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
