# Generated by Django 2.2.19 on 2021-05-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0013_peminjaman_barang_kode_pinjam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman_barang',
            name='id_barang',
            field=models.CharField(max_length=100),
        ),
    ]
