# Generated by Django 3.1.4 on 2021-06-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven', '0014_auto_20210529_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengembalian_barang',
            name='kode_pinjam',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
